//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.13 at 01:37:40 PM AEST 
//


package au.com.scds.agric.dom.demo;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.PersistenceCapable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.isis.applib.annotation.DomainObject;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormulationComponent", propOrder = {
    "ingredient",
    "quantity",
    "unit"
})
@DomainObject()
@PersistenceCapable(identityType = IdentityType.DATASTORE)
public class FormulationComponent {

	protected Formulation parentFormulation;
	@XmlElement(required = true)
    protected Ingredient ingredient;
    @XmlElement(required = true)
    protected Double quantity;
    @XmlElement(required = true)
    protected String unit;
    
    @Column(allowsNull="false")
    public Formulation getParentFormulation() {
		return parentFormulation;
	}

	public void setParentFormulation(Formulation parentFormulation) {
		this.parentFormulation = parentFormulation;
	}

	 @Column(allowsNull="false")
    public Ingredient getIngredient() {
        return ingredient;
    }

    public void setIngredient(Ingredient value) {
        this.ingredient = value;
    }

    @Column(allowsNull="false")
    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double value) {
        this.quantity = value;
    }

    @Column(allowsNull="false")
    public String getUnit() {
        return unit;
    }

    public void setUnit(String value) {
        this.unit = value;
    }

}
