//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.13 at 01:37:40 PM AEST 
//


package au.com.scds.agric.fixture.xml.generated2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * A batch of product, efficiently created in bulk for
 * 				subdivision into product-item lots.
 * 			
 * 
 * <p>Java class for FBatch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FBatch">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/AgricProducerSchema}FSampled">
 *       &lt;sequence>
 *         &lt;element name="created-on" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="created-by" type="{http://www.example.org/AgricProducerSchema}FPerson"/>
 *         &lt;element name="scheduled-for" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="completed-on" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="completed-by" type="{http://www.example.org/AgricProducerSchema}FPerson" minOccurs="0"/>
 *         &lt;element name="formulation" type="{http://www.example.org/AgricProducerSchema}FFormulation"/>
 *         &lt;element name="product-item" type="{http://www.example.org/AgricProducerSchema}FProductItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FBatch", propOrder = {
    "createdOn",
    "createdBy",
    "scheduledFor",
    "completedOn",
    "completedBy",
    "formulation",
    "productItem"
})
public class FBatch
    extends FSampled
{

    @XmlElement(name = "created-on", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdOn;
    @XmlElement(name = "created-by", required = true)
    protected FPerson createdBy;
    @XmlElement(name = "scheduled-for")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledFor;
    @XmlElement(name = "completed-on")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar completedOn;
    @XmlElement(name = "completed-by")
    protected FPerson completedBy;
    @XmlElement(required = true)
    protected FFormulation formulation;
    @XmlElement(name = "product-item")
    protected List<FProductItem> productItem;

    /**
     * Gets the value of the createdOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedOn() {
        return createdOn;
    }

    /**
     * Sets the value of the createdOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedOn(XMLGregorianCalendar value) {
        this.createdOn = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link FPerson }
     *     
     */
    public FPerson getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPerson }
     *     
     */
    public void setCreatedBy(FPerson value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the scheduledFor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledFor() {
        return scheduledFor;
    }

    /**
     * Sets the value of the scheduledFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledFor(XMLGregorianCalendar value) {
        this.scheduledFor = value;
    }

    /**
     * Gets the value of the completedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompletedOn() {
        return completedOn;
    }

    /**
     * Sets the value of the completedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompletedOn(XMLGregorianCalendar value) {
        this.completedOn = value;
    }

    /**
     * Gets the value of the completedBy property.
     * 
     * @return
     *     possible object is
     *     {@link FPerson }
     *     
     */
    public FPerson getCompletedBy() {
        return completedBy;
    }

    /**
     * Sets the value of the completedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPerson }
     *     
     */
    public void setCompletedBy(FPerson value) {
        this.completedBy = value;
    }

    /**
     * Gets the value of the formulation property.
     * 
     * @return
     *     possible object is
     *     {@link FFormulation }
     *     
     */
    public FFormulation getFormulation() {
        return formulation;
    }

    /**
     * Sets the value of the formulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FFormulation }
     *     
     */
    public void setFormulation(FFormulation value) {
        this.formulation = value;
    }

    /**
     * Gets the value of the productItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FProductItem }
     * 
     * 
     */
    public List<FProductItem> getProductItem() {
        if (productItem == null) {
            productItem = new ArrayList<FProductItem>();
        }
        return this.productItem;
    }

}
