//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.13 at 01:37:40 PM AEST 
//


package au.com.scds.agric.fixture.xml.generated2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FNewOrderLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FNewOrderLine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/AgricProducerSchema}FOrderLine">
 *       &lt;sequence>
 *         &lt;element name="added-on" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="added-by" type="{http://www.example.org/AgricProducerSchema}FPerson"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FNewOrderLine", propOrder = {
    "addedOn",
    "addedBy"
})
@XmlSeeAlso({
    FScheduledOrderLine.class
})
public class FNewOrderLine
    extends FOrderLine
{

    @XmlElement(name = "added-on", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar addedOn;
    @XmlElement(name = "added-by", required = true)
    protected FPerson addedBy;

    /**
     * Gets the value of the addedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAddedOn() {
        return addedOn;
    }

    /**
     * Sets the value of the addedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAddedOn(XMLGregorianCalendar value) {
        this.addedOn = value;
    }

    /**
     * Gets the value of the addedBy property.
     * 
     * @return
     *     possible object is
     *     {@link FPerson }
     *     
     */
    public FPerson getAddedBy() {
        return addedBy;
    }

    /**
     * Sets the value of the addedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPerson }
     *     
     */
    public void setAddedBy(FPerson value) {
        this.addedBy = value;
    }

}
