//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.13 at 01:37:40 PM AEST 
//


package au.com.scds.agric.fixture.xml.generated2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taken" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="taken-by" type="{http://www.example.org/AgricProducerSchema}FPerson"/>
 *         &lt;element name="order-line" type="{http://www.example.org/AgricProducerSchema}FNewOrderLine" maxOccurs="unbounded"/>
 *         &lt;element name="scheduled-order-line" type="{http://www.example.org/AgricProducerSchema}FScheduledOrderLine" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="completed-order-line" type="{http://www.example.org/AgricProducerSchema}FCompletedOrderLine" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FOrder", propOrder = {
    "taken",
    "takenBy",
    "orderLine",
    "scheduledOrderLine",
    "completedOrderLine"
})
public class FOrder {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar taken;
    @XmlElement(name = "taken-by", required = true)
    protected FPerson takenBy;
    @XmlElement(name = "order-line", required = true)
    protected List<FNewOrderLine> orderLine;
    @XmlElement(name = "scheduled-order-line")
    protected List<FScheduledOrderLine> scheduledOrderLine;
    @XmlElement(name = "completed-order-line")
    protected List<FCompletedOrderLine> completedOrderLine;

    /**
     * Gets the value of the taken property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTaken() {
        return taken;
    }

    /**
     * Sets the value of the taken property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTaken(XMLGregorianCalendar value) {
        this.taken = value;
    }

    /**
     * Gets the value of the takenBy property.
     * 
     * @return
     *     possible object is
     *     {@link FPerson }
     *     
     */
    public FPerson getTakenBy() {
        return takenBy;
    }

    /**
     * Sets the value of the takenBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FPerson }
     *     
     */
    public void setTakenBy(FPerson value) {
        this.takenBy = value;
    }

    /**
     * Gets the value of the orderLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FNewOrderLine }
     * 
     * 
     */
    public List<FNewOrderLine> getOrderLine() {
        if (orderLine == null) {
            orderLine = new ArrayList<FNewOrderLine>();
        }
        return this.orderLine;
    }

    /**
     * Gets the value of the scheduledOrderLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduledOrderLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduledOrderLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FScheduledOrderLine }
     * 
     * 
     */
    public List<FScheduledOrderLine> getScheduledOrderLine() {
        if (scheduledOrderLine == null) {
            scheduledOrderLine = new ArrayList<FScheduledOrderLine>();
        }
        return this.scheduledOrderLine;
    }

    /**
     * Gets the value of the completedOrderLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the completedOrderLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompletedOrderLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FCompletedOrderLine }
     * 
     * 
     */
    public List<FCompletedOrderLine> getCompletedOrderLine() {
        if (completedOrderLine == null) {
            completedOrderLine = new ArrayList<FCompletedOrderLine>();
        }
        return this.completedOrderLine;
    }

}
