//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.13 at 01:37:40 PM AEST 
//


package au.com.scds.agric.fixture.xml.generated2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.com.scds.agric.fixture.xml.generated2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Producer_QNAME = new QName("http://www.example.org/AgricProducerSchema", "producer");
    private final static QName _TestSuites_QNAME = new QName("http://www.example.org/AgricProducerSchema", "test-suites");
    private final static QName _Clients_QNAME = new QName("http://www.example.org/AgricProducerSchema", "clients");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.com.scds.agric.fixture.xml.generated2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FClients }
     * 
     */
    public FClients createFClients() {
        return new FClients();
    }

    /**
     * Create an instance of {@link FProducer }
     * 
     */
    public FProducer createFProducer() {
        return new FProducer();
    }

    /**
     * Create an instance of {@link FTestSuites }
     * 
     */
    public FTestSuites createFTestSuites() {
        return new FTestSuites();
    }

    /**
     * Create an instance of {@link FScheduledOrderLine }
     * 
     */
    public FScheduledOrderLine createFScheduledOrderLine() {
        return new FScheduledOrderLine();
    }

    /**
     * Create an instance of {@link FPerson }
     * 
     */
    public FPerson createFPerson() {
        return new FPerson();
    }

    /**
     * Create an instance of {@link FParty }
     * 
     */
    public FParty createFParty() {
        return new FParty();
    }

    /**
     * Create an instance of {@link FManufacturer }
     * 
     */
    public FManufacturer createFManufacturer() {
        return new FManufacturer();
    }

    /**
     * Create an instance of {@link FFormulation }
     * 
     */
    public FFormulation createFFormulation() {
        return new FFormulation();
    }

    /**
     * Create an instance of {@link FProductLine }
     * 
     */
    public FProductLine createFProductLine() {
        return new FProductLine();
    }

    /**
     * Create an instance of {@link FOrderLine }
     * 
     */
    public FOrderLine createFOrderLine() {
        return new FOrderLine();
    }

    /**
     * Create an instance of {@link FProductPack }
     * 
     */
    public FProductPack createFProductPack() {
        return new FProductPack();
    }

    /**
     * Create an instance of {@link FBatchComponent }
     * 
     */
    public FBatchComponent createFBatchComponent() {
        return new FBatchComponent();
    }

    /**
     * Create an instance of {@link FBatch }
     * 
     */
    public FBatch createFBatch() {
        return new FBatch();
    }

    /**
     * Create an instance of {@link FClient }
     * 
     */
    public FClient createFClient() {
        return new FClient();
    }

    /**
     * Create an instance of {@link FSupplier }
     * 
     */
    public FSupplier createFSupplier() {
        return new FSupplier();
    }

    /**
     * Create an instance of {@link FPurchaseOrder }
     * 
     */
    public FPurchaseOrder createFPurchaseOrder() {
        return new FPurchaseOrder();
    }

    /**
     * Create an instance of {@link FNewOrderLine }
     * 
     */
    public FNewOrderLine createFNewOrderLine() {
        return new FNewOrderLine();
    }

    /**
     * Create an instance of {@link FConsumer }
     * 
     */
    public FConsumer createFConsumer() {
        return new FConsumer();
    }

    /**
     * Create an instance of {@link FResult }
     * 
     */
    public FResult createFResult() {
        return new FResult();
    }

    /**
     * Create an instance of {@link FSampled }
     * 
     */
    public FSampled createFSampled() {
        return new FSampled();
    }

    /**
     * Create an instance of {@link FTestSuite }
     * 
     */
    public FTestSuite createFTestSuite() {
        return new FTestSuite();
    }

    /**
     * Create an instance of {@link FOrder }
     * 
     */
    public FOrder createFOrder() {
        return new FOrder();
    }

    /**
     * Create an instance of {@link FSupply }
     * 
     */
    public FSupply createFSupply() {
        return new FSupply();
    }

    /**
     * Create an instance of {@link FSample }
     * 
     */
    public FSample createFSample() {
        return new FSample();
    }

    /**
     * Create an instance of {@link FFormulationComponent }
     * 
     */
    public FFormulationComponent createFFormulationComponent() {
        return new FFormulationComponent();
    }

    /**
     * Create an instance of {@link FProductItem }
     * 
     */
    public FProductItem createFProductItem() {
        return new FProductItem();
    }

    /**
     * Create an instance of {@link FCompletedOrderLine }
     * 
     */
    public FCompletedOrderLine createFCompletedOrderLine() {
        return new FCompletedOrderLine();
    }

    /**
     * Create an instance of {@link FProductType }
     * 
     */
    public FProductType createFProductType() {
        return new FProductType();
    }

    /**
     * Create an instance of {@link FIngredient }
     * 
     */
    public FIngredient createFIngredient() {
        return new FIngredient();
    }

    /**
     * Create an instance of {@link FTest }
     * 
     */
    public FTest createFTest() {
        return new FTest();
    }

    /**
     * Create an instance of {@link FTestGroup }
     * 
     */
    public FTestGroup createFTestGroup() {
        return new FTestGroup();
    }

    /**
     * Create an instance of {@link FDelivery }
     * 
     */
    public FDelivery createFDelivery() {
        return new FDelivery();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FProducer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/AgricProducerSchema", name = "producer")
    public JAXBElement<FProducer> createProducer(FProducer value) {
        return new JAXBElement<FProducer>(_Producer_QNAME, FProducer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FTestSuites }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/AgricProducerSchema", name = "test-suites")
    public JAXBElement<FTestSuites> createTestSuites(FTestSuites value) {
        return new JAXBElement<FTestSuites>(_TestSuites_QNAME, FTestSuites.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FClients }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/AgricProducerSchema", name = "clients")
    public JAXBElement<FClients> createClients(FClients value) {
        return new JAXBElement<FClients>(_Clients_QNAME, FClients.class, null, value);
    }

}
