//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.31 at 07:50:58 AM AEDT 
//


package au.com.scds.agric.dom.demo.data;

import javax.jdo.annotations.Column;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderLineBatch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderLineBatch">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="percentage-of-batch" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderLineBatch", propOrder = {
    "batch",
    "percentageOfBatch"
})
public class OrderLineBatch {

	@XmlTransient
	@Column(allowsNull="false")
	protected OrderLine orderLine;
	@XmlElement
    @Column(allowsNull="false")
    protected Batch batch;
    @XmlElement(name = "percentage-of-batch")
    @Column(allowsNull="false")
    protected float percentageOfBatch;

	public OrderLine getOrderLine() {
		return orderLine;
	}

	public void setOrderLine(OrderLine orderLine) {
		this.orderLine = orderLine;
	}
	
    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Batch getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatch(Batch batch) {
        this.batch = batch;
    }

    /**
     * Gets the value of the percentageOfBatch property.
     * 
     */
    public float getPercentageOfBatch() {
        return percentageOfBatch;
    }

    /**
     * Sets the value of the percentageOfBatch property.
     * 
     */
    public void setPercentageOfBatch(float value) {
        this.percentageOfBatch = value;
    }

}
