//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 08:39:06 PM AEDT 
//

package au.com.scds.agric.dom.demo.data;

import java.util.ArrayList;
import java.util.List;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Inheritance;
import javax.jdo.annotations.InheritanceStrategy;
import javax.jdo.annotations.Join;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.isis.applib.annotation.DomainObject;

/**
 * A sample of a sampled item (product, batch, ingredient etc.) taken for
 * testing.
 * 
 * 
 * <p>
 * Java class for Sample complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Sample">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sampled" type="{http://www.example.org/AgricProducerSchema}Sampled"/>
 *         &lt;element name="test" type="{http://www.example.org/AgricProducerSchema}TestSingle" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="test-group" type="{http://www.example.org/AgricProducerSchema}TestGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="test-suite" type="{http://www.example.org/AgricProducerSchema}TestSuite" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="result" type="{http://www.example.org/AgricProducerSchema}Result" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sample", propOrder = { "sampled", "tests", "testGroups", "testSuites", "results" })
@DomainObject(objectType = "Sample")
@PersistenceCapable(identityType = IdentityType.DATASTORE)
@Inheritance(strategy = InheritanceStrategy.NEW_TABLE)
public class Sample {

	@XmlElement(required = true)
	@Column(allowsNull="false")
	protected Sampled sampled;
	@Join
	protected List<TestSingle> tests;
	@XmlElement(name = "test-group")
	@Join
	protected List<TestGroup> testGroups;
	@XmlElement(name = "test-suite")
	@Join
	protected List<TestSuite> testSuites;
	@Join
	protected List<Result> results;

	/**
	 * Gets the value of the sampled property.
	 * 
	 * @return possible object is {@link Sampled }
	 * 
	 */
	public Sampled getSampled() {
		return sampled;
	}

	/**
	 * Sets the value of the sampled property.
	 * 
	 * @param value
	 *            allowed object is {@link Sampled }
	 * 
	 */
	public void setSampled(Sampled value) {
		this.sampled = value;
	}

	/**
	 * Gets the value of the test property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the test property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTest().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TestSingle }
	 * 
	 * 
	 */
	public List<TestSingle> getTests() {
		return this.tests;
	}

	/**
	 * Gets the value of the testGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the testGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTestGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TestGroup
	 * }
	 * 
	 * 
	 */
	public List<TestGroup> getTestGroups() {
		return this.testGroups;
	}

	/**
	 * Gets the value of the testSuite property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the testSuite property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTestSuite().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link TestSuite
	 * }
	 * 
	 * 
	 */
	public List<TestSuite> getTestSuites() {
		return this.testSuites;
	}

	/**
	 * Gets the value of the result property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the result property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getResult().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Result }
	 * 
	 * 
	 */
	public List<Result> getResults() {
		return this.results;
	}

}
