//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 06:38:44 PM AEST 
//

package au.com.scds.agric.dom.demo.data;

import java.util.ArrayList;
import java.util.List;

import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Inheritance;
import javax.jdo.annotations.InheritanceStrategy;
import javax.jdo.annotations.PersistenceCapable;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.annotation.DomainObject;

@DomainObject(objectType = "SampleTestMultiple")
@PersistenceCapable(identityType = IdentityType.DATASTORE)
@Inheritance(strategy = InheritanceStrategy.NEW_TABLE)
public class TestMultiple {

	@Column(allowsNull = "false")
	protected Sample sample;
	@Column(allowsNull="false")
	protected int multiple;
	@Column(allowsNull="false")
	protected Test test;
    @Persistent(mappedBy="sampleTest")
	protected List<Result> results = new ArrayList<>();
    
	public Sample getSample() {
		return sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	public Test getTest() {
		return test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public int getMultiple() {
		return multiple;
	}

	public void setMultiple(int value) {
		this.multiple = value;
	}
	

	public List<Result> getResults() {
		return this.results;
	}

}
